### ISSUE TITLE
Strange binder issue

### ISSUE THREAD

**Issue by whyjz** [geostacks/GeoStacks#13]
I am testing if our notebooks work on both my `repo2docker` image and this binder link:
https://mybinder.org/v2/gh/geostacks/GeoStacks/main

Most notebooks are running well, but when I tried to open `doc/examples/WIP_EarthCube.ipynb`, it stuck at initiating a kernel and later disconnected. The same thing happens to my `repo2docker` image and the binder link. Any clues for that?

**Comment by espg** [comment]
@whyjz Yes-- you need to change the kernel. There should be two

- Python 3
- Python3 - python

You need to use the second one to access the kernel that has the right name space and items installed...

**Comment by whyjz** [comment]
Looks like #14 partially solves this issue, but there's another issue that seems to link to the pickle error we mentioned in #14. This is what happens if we open the binder that is pointing at @fperez's branch and try to run 'WIP_EarthCube.ipynb'.
![ScrSelection_018](https://user-images.githubusercontent.com/19339926/118066547-e123ed00-b36c-11eb-9f4a-197f17a7d8db.png)

**Comment by fperez** [comment]
I'm closing this, see further discussion in #14 - the bug is in mamba proper and for now we just need to work around the issue...
