### ISSUE TITLE
Setup continuous integration 

### ISSUE THREAD

**Issue by espg** [geostacks/GeoStacks#2]
Using github workflows, checking for:

- [ ] Installation (python 3.7, 3.8, 3.9 ; OSX, Linux, Windows)
- [x] Tests and testing (for when we have tests)

**Comment by whyjz** [comment]
With the latest commit to the main branch, a basic CI template has been set up and the Ubuntu+Python 3.7 has passed the test!

**Comment by espg** [comment]
Closing for now--  tests are run, don't think the code base is big enough to start testing for multiple versions of python or different OS's yet, although we can reopen at some point...
