### ISSUE TITLE
Something went wrong when calling dask Client

### ISSUE THREAD

**Issue by whyjz** [geostacks/GeoStacks#22]
I tried to run the notebook through but got stuck at this step:
![ScrSelection_023](https://user-images.githubusercontent.com/19339926/118346489-e1a5ba80-b509-11eb-9044-3e4409eb1bbe.png)
The message here is hard for me to debug... is this something related to a dependency issue? (I was installing dependencies with an existing conda environment instead of creating a new one of `GeoStacks`)

**Comment by espg** [comment]
my guess is that this either related to dependencies or perhaps in conflict with another install?

@whyjz I'm going to go ahead and close this-- the [binder](https://mybinder.org/v2/gh/geostacks/GeoStacks/earthcube) builds/runs fine, and so does the nix-shell install, so I think a clean build environment solves it-- reopen if it persists for you in a fresh conda environment...

**Comment by whyjz** [comment]
Yeah I think there are some hidden dependency issues. The fresh `geostacks` conda env works! And I found a missing hvplot dependency too.
